name: JammyBounties
version: '${project.version}'
main: me.vaindev.jammybounties.JammyBounties
api-version: 1.17
authors: [ vaindev ]
depend:
  - Vault
  - ProtocolLib
description: Bounties plugin by vaindev

commands:
  bounties:
    description: General Bounties Commands
    usage: /<command>
    permission: bounties.use
    aliases: [ bountygui, bounty, bounties, jammybounties, jbounties ]

permissions:
  bounties.use:
    description: Allows user to use & set bounties
    default: true
  bounties.claim:
      description: Allows user to claim bounties
      default: op
  bounties.admin:
    description: Gives user access to admin bounties commands
    default: op